
development:
  adapter: postgresql
  database: caioduarte_dev
  host: localhost
  username: caioduarte
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: caioduarte_test
  host: localhost
  username: caioduarte
  password:
  pool: 5
  timeout: 5000